#!/bin/sh

# Generates an inline GDB script that will be compiled into the kernel
# executable. This allows GDB to auto-load the script when debugging the kernel.

discard_change_warning()
{
    echo '   DO NOT EDIT THIS FILE! This file is automatically generated,' >> $1
    echo '   changes will be destroyed when regenerating! */' >> $1
    echo >> $1
}

out_file=gdb-script.c
echo '/* Inline GDB script for debugging PML kernels.' > $out_file
discard_change_warning $out_file
echo '#pragma GCC diagnostic ignored "-Wunused-variable"' >> $out_file
echo >> $out_file
echo '#define debug_section __attribute__ ((section (".debug_gdb_scripts")))' \
     >> $out_file
echo '#define char_align __attribute__ ((aligned (1)))' >> $out_file
echo >> $out_file
echo 'static unsigned char __gdb_script_type debug_section = 4;' >> $out_file
echo >> $out_file
echo 'static unsigned char __gdb_script_name[] debug_section char_align = {' \
     >> $out_file
echo "`echo $2 | $XXD -i`" >> $out_file
echo '};' >> $out_file
echo >> $out_file
echo 'static unsigned char __gdb_script[] debug_section char_align = {' >> \
     $out_file
echo "`$XXD -i < $1`" >> $out_file
echo '};' >> $out_file
echo >> $out_file
echo 'static unsigned char __gdb_script_null debug_section = 0;' >> $out_file
