import configparser
import sys

SYSTAB_HEADER = '''\
/* System call table for the x86-64 platform.
   DO NOT EDIT THIS FILE! This file was automatically generated by gensystab.py,
   changes will be destroyed when regenerating! */

#include <pml/syscall.h>

void *syscall_table[] = {
'''

if len(sys.argv) != 2:
    print('Usage: gensystab.py CONFIG', file=sys.stderr)
    sys.exit(1)

config = configparser.ConfigParser()
config.read(sys.argv[1])

with open('systab.c', 'w') as f:
    f.write(SYSTAB_HEADER)
    for syscall in config.sections():
        f.write('  [SYS_{0}] = sys_{0},\n'.format(syscall))
    f.write('};\n')
