#!/bin/sh

# Generates the system call table.

discard_change_warning()
{
    echo '   DO NOT EDIT THIS FILE! This file is automatically generated,' >> $1
    echo '   changes will be destroyed when regenerating! */' >> $1
    echo >> $1
}

tab_file=systab.c
echo '/* Syscall table for the x86-64 platform.' > $tab_file
discard_change_warning $tab_file
echo '#include <pml/syscall.h>' >> $tab_file
echo >> $tab_file
echo 'void *syscall_table[] = {' >> $tab_file

while IFS= read -r line; do
    case "$line" in
	"#"* )
	    continue
	    ;;
    esac
    [ -z "$line" ] && continue

    name=`echo $line | cut -f 2 -d ' '`
    echo "  [SYS_$name] = sys_$name," >> $tab_file
done < $1

echo '};' >> $tab_file
